/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : xlnt
 #	author : miyako
 #	2018/01/15
 #
 # --------------------------------------------------------------------------------*/

#include <xlnt/xlnt.hpp>

// --- xlnt
void xlnt_test(sLONG_PTR *pResult, PackagePtr pParams);
