/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : xlnt
 #	author : miyako
 #	2018/01/15
 #
 # --------------------------------------------------------------------------------*/

#include <xlnt/xlnt.hpp>

#include "libjson.h"

// --- xlnt
void xlnt_Workbook_from_blob(PA_PluginParameters params);
void xlnt_IMPORT_WORKBOOK(sLONG_PTR *pResult, PackagePtr pParams);

void xlnt_WORKBOOK_TO_BLOB(PA_PluginParameters params);
void xlnt_EXPORT_WORKBOOK(sLONG_PTR *pResult, PackagePtr pParams);

// --- Cleanup
void xlnt_CLEAR(sLONG_PTR *pResult, PackagePtr pParams);

// --- xlnt
void xlnt_SET_VALUES(sLONG_PTR *pResult, PackagePtr pParams);
void xlnt_GET_VALUES(sLONG_PTR *pResult, PackagePtr pParams);
